api = "0.6"

[buildpack]
  homepage = "https://github.com/paketo-community/web-servers"
  id = "paketo-community/web-server"
  name = "Paketo Web Servers Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-community/web-servers/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.1.2"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.5.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.0.2"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.1.2"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.2.1"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.0.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.0.2"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.0.2"

